name: Release Drafter
on: 
  push:
    branches:
    - master
jobs:
  build:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
    - uses: toolmantim/release-drafter@v5.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
