name: Build Vi-v

on:
- push
- pull_request

jobs:
  build:
    name: Build with ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: 
      - ${{ matrix.os }}
      - ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [X64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version master
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: master
      id: v
    - name: Build Vi-v
      run: |
        make
    - name: Test Vi-v
      run: |
        make test
